{
 "title": "IT-сектор и структура фондового рынка",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Распределение акций по странам",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(country) AS \"Country\",\n  COUNT(*) AS \"TotalCount\"\nFROM shares\nWHERE country IS NOT NULL\n  AND TRIM(country) <> ''\nGROUP BY country\nORDER BY TotalCount DESC;\n\n\n"
    }
   ]
  },
  {
   "title": "Оценка диверсификации рынка акций по странам (IT-сектор)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(country, ' (IT)') AS \"Country\",\n  COUNT(*) AS \"Count\"\nFROM shares\nWHERE country IS NOT NULL\n  AND TRIM(country) <> ''\n  AND sector LIKE '%IT%'\nGROUP BY country\nORDER BY Count DESC;\n"
    }
   ]
  },
  {
   "title": "Сравнение волатильности: IT vs Сырьевой сектор",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT s.sector AS \"Sector\", AVG(v.daily_volatility) AS \"Volatility\"\nFROM (\n  SELECT c1.figi,\n         STDDEV_SAMP((c1.close - c2.close) / c2.close) AS daily_volatility\n  FROM candle_year c1\n  JOIN candle_year c2 \n    ON c1.figi = c2.figi \n    AND DATE(c1.time) = DATE_ADD(DATE(c2.time), INTERVAL 1 DAY)\n  WHERE $__timeFilter(c1.time)\n  GROUP BY c1.figi\n) v\nJOIN shares s ON s.figi = v.figi\nWHERE s.sector IN ('it', 'materials')\nGROUP BY s.sector;\n\n"
    }
   ]
  },
  {
   "title": "Изменение самых дорогих IT-акций РФ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n  c.time AS time,\n  c.close AS value,\n  s.name AS metric\nFROM candle_year c\nJOIN shares s ON c.figi = s.figi\nWHERE c.figi IN (\n  'TCS00A107T19',\n  'TCS00A107ER5',\n  'TCS20A107662',\n  'TCS00A103X66',\n  'TCS00A10ANA1'\n)\nORDER BY c.time;\n"
    }
   ]
  }
 ]
}